AllowShopSigns: true
ShopCode: '[shop]'
SellingCode: '[buy]'
BuyingCode: '[sell]'
AdminShopName: 'The Bank'
UseItemEconomy: false
currency:
  Emerald: 1
  Emerald_Block: 9
offers:
  Enabled: false
  Regions: []
  ChunksPerTick: 1
  Interval: 60
sql:
  enable: false
