name: SimpleShop
description: Sell items via chests
version: 0.4
author: StarTux
depend: [ Vault ]
softdepend: [ LibSQL, WorldGuard ]
main: com.winthier.simpleshop.SimpleShopPlugin
commands:
  Shop:
    aliases: [ SimpleShop ]
    description: Shop command interface
    permission: simpleshop.shop
    usage: /<command> [args...]
permissions:
  simpleshop.shop:
    description: Use the "/shop" command
    default: op
  simpleshop.*:
    description: All privileges
    default: op
    children:
      simpleshop.shop: true
      simpleshop.stats: true
      simpleshop.search: true
      simpleshop.create.admin: true
      simpleshop.edit.admin: true
      simpleshop.create.other: true
      simpleshop.edit.other: true
      simpleshop.update: true
  simpleshop.create:
    description: Create a shop
    default: op
  simpleshop.create.other:
    description: Create a shop for another player
    default: op
  simpleshop.create.admin:
    description: Create an admin chest
    default: op
  simpleshop.edit:
    description: Edit the price tag of your shop
    default: op
  simpleshop.edit.other:
    description: Edit the price tag of another player's shop
    default: op
  simpleshop.edit.admin:
    description: Edit the price tag of an admin shop
    default: op
  simpleshop.import:
    description: Update the database schema
    default: op
  simpleshop.list:
    description: List your sales
    default: op
  simpleshop.average:
    description: Look up the average price via "/shop avg"
    default: op
  simpleshop.stats:
    description: Look up sales statistics
    default: op
  simpleshop.search:
    description: Search the market via "/shop search"
    default: op